# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Company.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "example.Company" do
    optional :name, :string, 1
  end
end

module Example
  Company = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Company").msgclass
end
