# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Image.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "example.Image" do
    optional :name, :string, 1
    optional :index, :int32, 2
  end
end

module Example
  Image = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Image").msgclass
end
