# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Importer.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "example.Importer" do
    optional :name, :string, 1
  end
end

module Example
  Importer = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Importer").msgclass
end
