# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Product.proto

require 'google/protobuf'

require 'Company_pb'
require 'Image_pb'
require 'Importer_pb'
require 'WarehouseProductInfo_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "example.Product" do
    optional :name, :string, 1
    optional :code, :string, 2
    optional :quantity, :int32, 3
    optional :company, :message, 4, "example.Company"
    repeated :image, :message, 5, "example.Image"
    optional :importer, :message, 6, "example.Importer"
    optional :warehouseProductInfo, :message, 7, "example.WarehouseProductInfo"
  end
end

module Example
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Product").msgclass
end
