# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WarehouseProductInfo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "example.WarehouseProductInfo" do
    optional :quantity, :int32, 1
  end
end

module Example
  WarehouseProductInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.WarehouseProductInfo").msgclass
end
