# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Product.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Company_pb2 as Company__pb2
import Image_pb2 as Image__pb2
import Importer_pb2 as Importer__pb2
import WarehouseProductInfo_pb2 as WarehouseProductInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Product.proto',
  package='example',
  syntax='proto3',
  serialized_pb=_b('\n\rProduct.proto\x12\x07\x65xample\x1a\rCompany.proto\x1a\x0bImage.proto\x1a\x0eImporter.proto\x1a\x1aWarehouseProductInfo.proto\"\xdb\x01\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12!\n\x07\x63ompany\x18\x04 \x01(\x0b\x32\x10.example.Company\x12\x1d\n\x05image\x18\x05 \x03(\x0b\x32\x0e.example.Image\x12#\n\x08importer\x18\x06 \x01(\x0b\x32\x11.example.Importer\x12;\n\x14warehouseProductInfo\x18\x07 \x01(\x0b\x32\x1d.example.WarehouseProductInfoB\'\n\x17\x63om.example.protocolbufB\x0cProductProtob\x06proto3')
  ,
  dependencies=[Company__pb2.DESCRIPTOR,Image__pb2.DESCRIPTOR,Importer__pb2.DESCRIPTOR,WarehouseProductInfo__pb2.DESCRIPTOR,])




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='example.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.Product.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='example.Product.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='example.Product.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company', full_name='example.Product.company', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='example.Product.image', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='importer', full_name='example.Product.importer', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='warehouseProductInfo', full_name='example.Product.warehouseProductInfo', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=318,
)

_PRODUCT.fields_by_name['company'].message_type = Company__pb2._COMPANY
_PRODUCT.fields_by_name['image'].message_type = Image__pb2._IMAGE
_PRODUCT.fields_by_name['importer'].message_type = Importer__pb2._IMPORTER
_PRODUCT.fields_by_name['warehouseProductInfo'].message_type = WarehouseProductInfo__pb2._WAREHOUSEPRODUCTINFO
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'Product_pb2'
  # @@protoc_insertion_point(class_scope:example.Product)
  ))
_sym_db.RegisterMessage(Product)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027com.example.protocolbufB\014ProductProto'))
# @@protoc_insertion_point(module_scope)
