# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Products.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Product_pb2 as Product__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Products.proto',
  package='example',
  syntax='proto3',
  serialized_pb=_b('\n\x0eProducts.proto\x12\x07\x65xample\x1a\rProduct.proto\".\n\x08Products\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.example.ProductB(\n\x17\x63om.example.protocolbufB\rProductsProtob\x06proto3')
  ,
  dependencies=[Product__pb2.DESCRIPTOR,])




_PRODUCTS = _descriptor.Descriptor(
  name='Products',
  full_name='example.Products',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='products', full_name='example.Products.products', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=88,
)

_PRODUCTS.fields_by_name['products'].message_type = Product__pb2._PRODUCT
DESCRIPTOR.message_types_by_name['Products'] = _PRODUCTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Products = _reflection.GeneratedProtocolMessageType('Products', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCTS,
  __module__ = 'Products_pb2'
  # @@protoc_insertion_point(class_scope:example.Products)
  ))
_sym_db.RegisterMessage(Products)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027com.example.protocolbufB\rProductsProto'))
# @@protoc_insertion_point(module_scope)
